language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-doc-metrix-doc' ]; then cd .. && eval "mv $currentfolder generator-doc-metrix-doc" && cd generator-doc-metrix-doc; fi
after_script:
  - npm run coveralls

