language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-doc-metrix-spec' ]; then cd .. && eval "mv $currentfolder generator-doc-metrix-spec" && cd generator-doc-metrix-spec; fi
after_script:
  - npm run coveralls

